question_id_dict = {
    '166337053': 'q1', # ÅF-nummer
    '166337054': 'q2', # Skaparen av denna analys (ditt namn)
    '166337056': 'q3', # Org. nummer
    '166336900': 'q4', # Företagets namn: (custCompName)
    '166338171': 'q5', # Antal bilar i vagnsparken
    '166338436': 'q6', # Kontaktpersonens Namn:
    '166338327': 'q7', # Kontaktpersonens mailadress:
    '166337737': 'q8', # Kontaktpersonens telefonnummer:
    '166336915': 'q9',
    '166336899': 'q10',
    '166336916': 'q11',
    '166336917': 'q12',
    '166336918': 'q13',
    '166336949': 'q14',
    '166336919': 'q15',
    '166336914': 'q16',
    '166336920': 'q17',
    '166336921': 'q18',
    '166336906': 'q19',
    '166336922': 'q20',
    '166336905': 'q21',
    '166336923': 'q22',
    '166336924': 'q23',
    '166336925': 'q24',
    '166336926': 'q25',
    '166336927': 'q26',
    '166336928': 'q27',
    '166336902': 'q28',
    '166336907': 'q29',
    '166361858': 'q30',
    '166336908': 'q31',
    '166336909': 'q32',
    '166336930': 'q33',
    '166336910': 'q34',
    '166336911': 'q35',
    '166336929': 'q36',
    '166336931': 'q37',
    '166336932': 'q38',
    '166336933': 'q39',
    '166336969': 'q40',
    '166336970': 'q41',
    '166368752': 'q42',
    '166336971': 'q43',
    '166336972': 'q44',
    '166336973': 'q45',
    '166337010': 'q46',
    '166337011': 'q47',
    '166337024': 'q48',
    '166337037': 'q49',
    '166337044': 'q50',
    '166337031': 'q51',
    '166336975': 'q52',
    '166336976': 'q53',
    '166370143': 'q54',
    '166336977': 'q55',
    '166336978': 'q56',
    '166336979': 'q57',
    '166337012': 'q58',
    '166337013': 'q59',
    '166337025': 'q60',
    '166337038': 'q61',
    '166337045': 'q62',
    '166337032': 'q63',
    '166336981': 'q64',
    '166336982': 'q65',
    '166371472': 'q66',
    '166336983': 'q67',
    '166336984': 'q68',
    '166336985': 'q69',
    '166337014': 'q70',
    '166337015': 'q71',
    '166337026': 'q72',
    '166337039': 'q73',
    '166337046': 'q74',
    '166337033': 'q75',
    '166336987': 'q76',
    '166336988': 'q77',
    '166372777': 'q78',
    '166336989': 'q79',
    '166336990': 'q80',
    '166336991': 'q81',
    '166337016': 'q82',
    '166337017': 'q83',
    '166337027': 'q84',
    '166337040': 'q85',
    '166337047': 'q86',
    '166337034': 'q87',
    '166336993': 'q88',
    '166336994': 'q89',
    '166373890': 'q90',
    '166336995': 'q91',
    '166336996': 'q92',
    '166336997': 'q93',
    '166337018': 'q94',
    '166337019': 'q95',
    '166337028': 'q96',
    '166337041': 'q97',
    '166337048': 'q98',
    '166337035': 'q99',
    '166336999': 'q100',
    '166337000': 'q101',
    '166374906': 'q102',
    '166337001': 'q103',
    '166337002': 'q104',
    '166337003': 'q105',
    '166337020': 'q106',
    '166337021': 'q107',
    '166337029': 'q108',
    '166337042': 'q109',
    '166337049': 'q110',
    '166337036': 'q111',
    '166337005': 'q112',
    '166337006': 'q113',
    '166375681': 'q114',
    '166337007': 'q115',
    '166337008': 'q116',
    '166337009': 'q117',
    '166337022': 'q118',
    '166337023': 'q119',
    '166337030': 'q120',
    '166337043': 'q121',
    '166337050': 'q122',
    '166336934': 'q123',
    '166336935': 'q124',
    '166336936': 'q125',
    '166336937': 'q126',
    '166336938': 'q127',
    '166336939': 'q128',
    '166336940': 'q129',
    '166336941': 'q130',
    '166336942': 'q131',
    '166336943': 'q132',
    '166336944': 'q133',
    '166337051': 'q134',
    '166336945': 'q135',
    '166336946': 'q136',
    '166336947': 'q137',
    '166336948': 'q138',
    '166336950': 'q139',
    '166336951': 'q140',
    '166336952': 'q141',
    '166336953': 'q142',
    '166336954': 'q143',
    '166336955': 'q144',
    '166336956': 'q145',
    '166336957': 'q146',
    '166336958': 'q147',
    '166336959': 'q148',
    '166336960': 'q149',
    '166336961': 'q150',
    '166336962': 'q151',
    '166336904': 'q152',
    '166337061': 'q153',
    '166378939': 'q154',
    '166379117': 'q155',
    '166379191': 'q156',
    '166379255': 'q157',
    '166337062': 'q158',
    '166337063': 'q159',
    '166336903': 'q160',
    '166336966': 'q161',
    '166336967': 'q162',
    '166336963': 'q163',
    '166337057': 'q164',
    '166337065': 'q165',
    '166337058': 'q166',
    '166337059': 'q167',
    '166337060': 'q168',
    '166337064': 'q169',
    '166384842': 'q170',
    '166384743': 'q171',
    '166336964': 'q172',
}

question_dict = {
    'q1': 'ÅF-nummer',
    'q2': 'Intervjuare',
    'q3': 'Org. nummer',
    'q4': 'Företagets namn',
    'q5': 'Antal bilar i vagnparken',
    'q6': 'Kontaktperson',
    'q7': 'Mailadress',
    'q8': 'Telefonnummer',
    'q9': 'Hur vill ni att era kunder ska uppfatta ert val av bilar?',
    'q10': 'Hur viktigt är det att bilarna matchar ert varumärke? (På en femgradig skala där 1 = "Inte alls viktigt" till 5 = "mycket viktigt")',
    'q11': 'Vad är er image och vad vill ni kommunicera med bilarna?',
    'q12': 'Vad är det ni inte är nöjda med med och planerar ni att åtgärda detta?',
    'q13': 'Hur nöjda är ni med hur era nuvarande bilar matchar ert varumärke? (1 = "mycket missnöjda" och 5 = "mycket nöjda")',
    'q14': 'Stripar ni några av bilarna?',
    'q15': 'Vilka bilar stripar ni? Hur stripas dom? Vem stripar dem? Kostnad?',
    'q16': 'Hur viktigt är det att minimera bilarnas miljöpåverkan? ( 5 = mycket viktigt)',
    'q17': 'Hur påverkas er verksamhet av bilarnas miljövänlighet?',
    'q18': 'Har ni några mål eller krav kring bilarnas miljöpåverkan? (Tips: Co2, kolväten, partiklar, dubbdäck)',
    'q19': 'Hur nöjda är ni med nuvarande vagnparks miljöpåverkan? ( 5 = "mycket nöjda")',
    'q20': 'Vad är det ni inte är nöjda med och har ni några planer på att åtgärda detta?',
    'q21': 'Hur viktigt är de för er att ha attraktiva tjänste- och förmånsbilar i rekryteringssyfte? ( 5 = "mycket viktigt")',
    'q22': 'Vad är er arbetsgivarerimage och vad vill ni att era bilar och bilpolicy ska kommuicera till potentiella medarbetare?',
    'q23': 'Vilka roller är svår-rekryterade och hur viktigt är det att kandidaterna inte tackar nej till era jobberbjudanden?',
    'q24': 'Hur viktigt är det att era medarbetare är nöjda med bilarna de får köra? (5 = "mycket viktigt")',
    'q25': 'Har medarbetarna några önskemål på bilpolicyn eller bilarna?',
    'q26': 'Vad har de för önskemål eller klagomål?',
    'q27': 'Vilka säkerhetskriterier har ni för bilarna?',
    'q28': 'Förargrupp 1: Ange en benämning för gruppen förare',
    'q29': 'Vilka yrkesroller/tjänster ingår i gruppen?',
    'q30': 'Hur många bilar nyttjas av gruppen?',
    'q31': 'Fordonens huvudsakliga tillhörighet:',
    'q32': 'Krav på bilarna för denna förargrupp?',
    'q33': 'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'q34': 'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'q35': 'Får ni höra klagomål eller synpunkter från dessa förare?',
    'q36': 'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'q37': 'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'q38': 'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'q39': 'Finns det någon annan förargrupp som använder företagets bilar?',
    'q40': 'Ange en benämning på förargrupp 2:',
    'q41': 'Vilka yrkesroller/tjänster ingår i gruppen?',
    'q42': 'Hur många bilar nyttjas av gruppen?',
    'q43': 'Fordonens huvudsakliga tillhörighet:',
    'q44': 'Krav på bilarna för denna förargrupp?',
    'q45': 'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'q46': 'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'q47': 'Får ni höra klagomål eller synpunkter från dessa förare?',
    'q48': 'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'q49': 'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'q50': 'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'q51': 'Vi har nu identifierat 2 förargrupper. Finns det ytterligare någon förargrupp som använder företagets bilar?',
    'q52': 'Ange en benämning på förargrupp 3:',
    'q53': 'Vilka yrkesroller/tjänster ingår i gruppen?',
    'q54': 'Hur många bilar nyttjas av gruppen?',
    'q55': 'Fordonens huvudsakliga tillhörighet:',
    'q56': 'Krav på bilarna för denna förargrupp?',
    'q57': 'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'q58': 'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'q59': 'Får ni höra klagomål eller synpunkter från dessa förare?',
    'q60': 'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'q61': 'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'q62': 'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'q63': 'Vi har nu identifierat 3 förargrupper. Finns det ytterligare någon förargrupp som använder företagets bilar?',
    'q64': 'Ange en benämning på förargrupp 4:',
    'q65': 'Vilka yrkesroller/tjänster ingår i gruppen?',
    'q66': 'Hur många bilar nyttjas av gruppen?',
    'q67': 'Fordonens huvudsakliga tillhörighet:',
    'q68': 'Krav på bilarna för denna förargrupp?',
    'q69': 'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'q70': 'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'q71': 'Får ni höra klagomål eller synpunkter från dessa förare?',
    'q72': 'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'q73': 'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'q74': 'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'q75': 'Vi har nu identifierat 4 förargrupper. Finns det någon annan förargrupp som använder företagets bilar?',
    'q76': 'Ange en benämning på förargrupp 5:',
    'q77': 'Vilka yrkesroller/tjänster ingår i gruppen?',
    'q78': 'Hur många bilar nyttjas av gruppen?',
    'q79': 'Fordonens huvudsakliga tillhörighet:',
    'q80': 'Krav på bilarna för denna förargrupp?',
    'q81': 'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'q82': 'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'q83': 'Får ni höra klagomål eller synpunkter från dessa förare?',
    'q84': 'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'q85': 'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'q86': 'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'q87': 'Vi har nu identifierat 5 förargrupper. Finns det någon annan förargrupp som använder företagets bilar?',
    'q88': 'Ange en benämning på förargrupp 6:',
    'q89': 'Vilka yrkesroller/tjänster ingår i gruppen?',
    'q90': 'Hur många bilar nyttjas av gruppen?',
    'q91': 'Fordonens huvudsakliga tillhörighet:',
    'q92': 'Krav på bilarna för denna förargrupp?',
    'q93': 'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'q94': 'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'q95': 'Får ni höra klagomål eller synpunkter från dessa förare?',
    'q96': 'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'q97': 'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'q98': 'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'q99': 'Vi har nu identifierat 6 förargrupper. Finns det någon annan förargrupp som använder företagets bilar?',
    'q100': 'Ange en benämning på förargrupp 7:',
    'q101': 'Vilka yrkesroller/tjänster ingår i gruppen?',
    'q102': 'Hur många bilar nyttjas av gruppen?',
    'q103': 'Fordonens huvudsakliga tillhörighet:',
    'q104': 'Krav på bilarna för denna förargrupp?',
    'q105': 'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'q106': 'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'q107': 'Får ni höra klagomål eller synpunkter från dessa förare?',
    'q108': 'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'q109': 'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'q110': 'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'q111': 'Vi har nu identifierat 7 förargrupper. Vi har utrymmer för ytterligare en. Finns det någon slutlig förargrupp som använder företagets bilar?',
    'q112': 'Ange en benämning på förargrupp 8:',
    'q113': 'Vilka yrkesroller/tjänster ingår i den gruppen?',
    'q114': 'Hur många bilar nyttjas av gruppen?',
    'q115': 'Fordonens huvudsakliga tillhörighet:',
    'q116': 'Krav på bilarna för denna förargrupp?',
    'q117': 'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'q118': 'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'q119': 'Får ni höra klagomål eller synpunkter från dessa förare?',
    'q120': 'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'q121': 'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'q122': 'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'q123': 'Estimerar ni månadskostnaden - och i så fall hur?',
    'q124': 'Hur länge behåller ni bilarna? (mil / ålder)',
    'q125': 'Har ni några besparingsmål?',
    'q126': 'Vad är besparingsmålen och har ni planer på att spara in på billösningen?',
    'q127': 'Vad har ni för ägandeform på bilarna?',
    'q128': 'Hur viktigt är det att minimera risken för oväntat låga priser på andrahandsmarknaden?',
    'q129': 'Varför har ni operationell leasing? (Trots att det inte är viktigt att minimera risken för oväntat låga andrahandsvärden)',
    'q130': 'Hur nöjda är ni med att ha finansiell leasing  - givet risken detta medför?',
    'q131': 'Vad är ni inte nöjda med och har ni några planer på att åtgärda detta?',
    'q132': 'Hur estimerar ni den verkliga månadskostnaden för bilarna? VIlka kostnader räknar ni in?',
    'q133': 'Hur säkerställer ni att inte bilar med höga månadskostnader och hög risk för låga andrahandsvärden plockas ut?',
    'q134': 'Vilket finansbolag använder ni?',
    'q135': 'Vem sköter administrationen?',
    'q136': 'Är ni missnöjda med något med finansieringslösningen eller administrationen?',
    'q137': 'Vad är ni missnöjda med? Planerar ni att åtgärda detta?',
    'q138': 'Får ni dra av momsen?',
    'q139': 'Hur nöjda är ni med arbetstiden förarna spenderar på att välja bil?',
    'q140': 'Hur lång tid spenderar de på att välja bil? Planerar ni att åtgärda detta?',
    'q141': 'Hur nöjda är ni med arbetstiden det tar er att hjälpa förarna att välja bil och beställa den (exempel; förklara valmöjligheter, offertförfrågan, förmånsvärden, orderläggning)?',
    'q142': 'Vad är det ni är missnöjda med och planerar ni att åtgärda detta?',
    'q143': 'Blir det någonsin fel i ärendehanteringen?',
    'q144': 'Vilka fel har inträffat? Planerar ni att åtgärda detta?',
    'q145': 'Hur avyttrar ni bilarna?',
    'q146': 'Har ni några dotterbolag?',
    'q147': 'Hur skiljer sig bilpolicyn mellan dotterbolagen? Har ni några planer på att samordna bilpolicy inom koncernen?',
    'q148': 'Är ni ett dotterbolag?',
    'q149': 'Vad har ni för riktlinjer kring bilpolicyn och billösningen från moderbolaget?',
    'q150': 'Vad har ni för bilavtal på koncernbolagsnivå?',
    'q151': 'Samarbetar ni med systerbolagen kring bilfrågorna?',
    'q152': 'Vilken är den senaste förändring av fordonsparken / bilpolicyn som ni genomfört?',
    'q153': 'När genomförde ni förändringen?',
    'q154': 'Vem tog fram förslaget?',
    'q155': 'Vem/vilka fattade beslutet om förändring?',
    'q156': 'Vilka var med på beslutsmötet?',
    'q157': 'Vilka var tillfrågade?',
    'q158': 'Vad hoppades ni uppnå med förändringen?',
    'q159': 'Vad var det som föranledde förändringen?',
    'q160': 'Planerar ni att göra någon ändring av er bilpolicy eller billösning?',
    'q161': 'Vilka ändringar planerar ni och när?',
    'q162': 'Vad föranledde att ni prioriterar denna ändring?',
    'q163': 'Har ni någon upphandling på gång?',
    'q164': 'Deadline?',
    'q165': 'Vad händer om ni inte är klara med upphandlingen innan deadline?',
    'q166': 'Vad hoppas ni uppnå med förändringen?',
    'q167': 'Vad föranledde upphandlingen?',
    'q168': 'Planerad upphandlingsprocess inkl milstolpar?',
    'q169': 'Om beslutsfattandet: Vem tar fram förslaget?',
    'q170': 'Vem / vilka fattar beslutet?',
    'q171': 'Vilka tillfrågas?',
    'q172': 'Innan vi avrundar och jag skickar in behovsanalysen, är det något du vill lägga till - något som vi missat under genomgången?'
}

question_list = [
    'ÅF-nummer',
    'Intervjuare',
    'Org. nummer',
    'Företagets namn',
    'Antal bilar i vagnparken',
    'Kontaktperson',
    'Mailadress',
    'Telefonnummer',
    'Hur vill ni att era kunder ska uppfatta ert val av bilar?',
    'Hur viktigt är det att bilarna matchar ert varumärke? (På en femgradig skala där 1 = "Inte alls viktigt" till 5 = "mycket viktigt")',
    'Vad är er image och vad vill ni kommunicera med bilarna?',
    'Vad är det ni inte är nöjda med med och planerar ni att åtgärda detta?',
    'Hur nöjda är ni med hur era nuvarande bilar matchar ert varumärke? (1 = "mycket missnöjda" och 5 = "mycket nöjda")',
    'Stripar ni några av bilarna?',
    'Vilka bilar stripar ni? Hur stripas dom? Vem stripar dem? Kostnad?',
    'Hur viktigt är det att minimera bilarnas miljöpåverkan? ( 5 = mycket viktigt)',
    'Hur påverkas er verksamhet av bilarnas miljövänlighet?',
    'Har ni några mål eller krav kring bilarnas miljöpåverkan? (Tips: Co2, kolväten, partiklar, dubbdäck)',
    'Hur nöjda är ni med nuvarande vagnparks miljöpåverkan? ( 5 = "mycket nöjda")',
    'Vad är det ni inte är nöjda med och har ni några planer på att åtgärda detta?',
    'Hur viktigt är de för er att ha attraktiva tjänste- och förmånsbilar i rekryteringssyfte? ( 5 = "mycket viktigt")',
    'Vad är er arbetsgivarerimage och vad vill ni att era bilar och bilpolicy ska kommuicera till potentiella medarbetare?',
    'Vilka roller är svår-rekryterade och hur viktigt är det att kandidaterna inte tackar nej till era jobberbjudanden?',
    'Hur viktigt är det att era medarbetare är nöjda med bilarna de får köra? (5 = "mycket viktigt")',
    'Har medarbetarna några önskemål på bilpolicyn eller bilarna?',
    'Vad har de för önskemål eller klagomål?',
    'Vilka säkerhetskriterier har ni för bilarna?',
    'Förargrupp 1: Ange en benämning för gruppen förare',
    'Vilka yrkesroller/tjänster ingår i gruppen?',
    'Hur många bilar nyttjas av gruppen?',
    'Fordonens huvudsakliga tillhörighet:',
    'Krav på bilarna för denna förargrupp?',
    'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'Får ni höra klagomål eller synpunkter från dessa förare?',
    'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'Finns det någon annan förargrupp som använder företagets bilar?',
    'Förargrupp 2:',
    'Vilka yrkesroller/tjänster ingår i gruppen?',
    'Hur många bilar nyttjas av gruppen?',
    'Fordonens huvudsakliga tillhörighet:',
    'Krav på bilarna för denna förargrupp?',
    'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'Får ni höra klagomål eller synpunkter från dessa förare?',
    'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'Vi har nu identifierat 2 förargrupper. Finns det ytterligare någon förargrupp som använder företagets bilar?',
    'Förargrupp 3:',
    'Vilka yrkesroller/tjänster ingår i gruppen?',
    'Hur många bilar nyttjas av gruppen?',
    'Fordonens huvudsakliga tillhörighet:',
    'Krav på bilarna för denna förargrupp?',
    'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'Får ni höra klagomål eller synpunkter från dessa förare?',
    'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'Vi har nu identifierat 3 förargrupper. Finns det ytterligare någon förargrupp som använder företagets bilar?',
    'Förargrupp 4:',
    'Vilka yrkesroller/tjänster ingår i gruppen?',
    'Hur många bilar nyttjas av gruppen?',
    'Fordonens huvudsakliga tillhörighet:',
    'Krav på bilarna för denna förargrupp?',
    'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'Får ni höra klagomål eller synpunkter från dessa förare?',
    'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'Vi har nu identifierat 4 förargrupper. Finns det någon annan förargrupp som använder företagets bilar?',
    'Förargrupp 5:',
    'Vilka yrkesroller/tjänster ingår i gruppen?',
    'Hur många bilar nyttjas av gruppen?',
    'Fordonens huvudsakliga tillhörighet:',
    'Krav på bilarna för denna förargrupp?',
    'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'Får ni höra klagomål eller synpunkter från dessa förare?',
    'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'Vi har nu identifierat 5 förargrupper. Finns det någon annan förargrupp som använder företagets bilar?',
    'Förargrupp 6:',
    'Vilka yrkesroller/tjänster ingår i gruppen?',
    'Hur många bilar nyttjas av gruppen?',
    'Fordonens huvudsakliga tillhörighet:',
    'Krav på bilarna för denna förargrupp?',
    'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'Får ni höra klagomål eller synpunkter från dessa förare?',
    'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'Vi har nu identifierat 6 förargrupper. Finns det någon annan förargrupp som använder företagets bilar?',
    'Förargrupp 7:',
    'Vilka yrkesroller/tjänster ingår i gruppen?',
    'Hur många bilar nyttjas av gruppen?',
    'Fordonens huvudsakliga tillhörighet:',
    'Krav på bilarna för denna förargrupp?',
    'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'Får ni höra klagomål eller synpunkter från dessa förare?',
    'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'Vi har nu identifierat 7 förargrupper. Vi har utrymmer för ytterligare en. Finns det någon slutlig förargrupp som använder företagets bilar?',
    'Förargrupp 8:',
    'Vilka yrkesroller/tjänster ingår i den gruppen?',
    'Hur många bilar nyttjas av gruppen?',
    'Fordonens huvudsakliga tillhörighet:',
    'Krav på bilarna för denna förargrupp?',
    'Finns det några kostnadsbegränsningar för förargruppen (t.ex basbelopp)?',
    'Hur och var används dessa bilar i tjänsten? (Speciella behov utöver normal körning)',
    'Får ni höra klagomål eller synpunkter från dessa förare?',
    'Vilka klagomål eller synpunkter? Hur ofta? Planerar ni göra något åt detta?',
    'Hur viktigt är det att dessa förare inte står utan bil temporärt? ( 5 = "mycket viktigt")',
    'Vad gör ni för att undvika att dessa förare står utan bil temporärt?',
    'Estimerar ni månadskostnaden - och i så fall hur?',
    'Hur länge behåller ni bilarna? (mil / ålder)',
    'Har ni några besparingsmål?',
    'Vad är besparingsmålen och har ni planer på att spara in på billösningen?',
    'Vad har ni för ägandeform på bilarna?',
    'Hur viktigt är det att minimera risken för oväntat låga priser på andrahandsmarknaden?',
    'Varför har ni operationell leasing? (Trots att det inte är viktigt att minimera risken för oväntat låga andrahandsvärden)',
    'Hur nöjda är ni med att ha finansiell leasing  - givet risken detta medför?',
    'Vad är ni inte nöjda med och har ni några planer på att åtgärda detta?',
    'Hur estimerar ni den verkliga månadskostnaden för bilarna? VIlka kostnader räknar ni in?',
    'Hur säkerställer ni att inte bilar med höga månadskostnader och hög risk för låga andrahandsvärden plockas ut?',
    'Vilket finansbolag använder ni?',
    'Vem sköter administrationen?',
    'Är ni missnöjda med något med finansieringslösningen eller administrationen?',
    'Vad är ni missnöjda med? Planerar ni att åtgärda detta?',
    'Får ni dra av momsen?',
    'Hur nöjda är ni med arbetstiden förarna spenderar på att välja bil?',
    'Hur lång tid spenderar de på att välja bil? Planerar ni att åtgärda detta?',
    'Hur nöjda är ni med arbetstiden det tar er att hjälpa förarna att välja bil och beställa den (exempel; förklara valmöjligheter, offertförfrågan, förmånsvärden, orderläggning)?',
    'Vad är det ni är missnöjda med och planerar ni att åtgärda detta?',
    'Blir det någonsin fel i ärendehanteringen?',
    'Vilka fel har inträffat? Planerar ni att åtgärda detta?',
    'Hur avyttrar ni bilarna?',
    'Har ni några dotterbolag?',
    'Hur skiljer sig bilpolicyn mellan dotterbolagen? Har ni några planer på att samordna bilpolicy inom koncernen?',
    'Är ni ett dotterbolag?',
    'Vad har ni för riktlinjer kring bilpolicyn och billösningen från moderbolaget?',
    'Vad har ni för bilavtal på koncernbolagsnivå?',
    'Samarbetar ni med systerbolagen kring bilfrågorna?',
    'Vilken är den senaste förändring av fordonsparken / bilpolicyn som ni genomfört?',
    'När genomförde ni förändringen?',
    'Vem tog fram förslaget?',
    'Vem/vilka fattade beslutet om förändring?',
    'Vilka var med på beslutsmötet?',
    'Vilka var tillfrågade?',
    'Vad hoppades ni uppnå med förändringen?',
    'Vad var det som föranledde förändringen?',
    'Planerar ni att göra någon ändring av er bilpolicy eller billösning?',
    'Vilka ändringar planerar ni och när?',
    'Vad föranledde att ni prioriterar denna ändring?',
    'Har ni någon upphandling på gång?',
    'Deadline?',
    'Vad händer om ni inte är klara med upphandlingen innan deadline?',
    'Vad hoppas ni uppnå med förändringen?',
    'Vad föranledde upphandlingen?',
    'Planerad upphandlingsprocess inkl milstolpar?',
    'Om beslutsfattandet: Vem tar fram förslaget?',
    'Vem / vilka fattar beslutet?',
    'Vilka tillfrågas?',
    'Innan vi avrundar och jag skickar in behovsanalysen, är det något du vill lägga till - något som vi missat under genomgången?'
]